### ISSUE TITLE
CSS width fixed at 210px?

### ISSUE THREAD

**Issue by ksnyde** [seiyria/bootstrap-slider#279]
````css
.slider.slider-horizontal {
    width: 100%;
}
````

There is a static reference to width of 210px for horizontal sliders. This seems pretty arbitrary and obviously can be overwritten (aka, cascaded over) in your own CSS but why not just set this to 100%? I have this setting and it works fine in all the use cases I've found.
