### ISSUE TITLE
Border-radius uses mixin?

### ISSUE THREAD

**Issue by DaNiiL4** [seiyria/bootstrap-slider#377]
In slider sccss file 
```css
.slider-track-low, .slider-track-high {
  position: absolute;
  background: transparent;
  @include box-sizing(border-box);
  border-radius: border-radius($baseBorderRadius);
}
```
border-radius doesn't work at all, why don't you use border-radius mixin?
