### ISSUE TITLE
printing sliders

### ISSUE THREAD

**Issue by bkingsf** [seiyria/bootstrap-slider#537]
The slider works great for me with one exception. When I try to print it the tracks don't show. This is demonstrable on your examples page by using the browser print option.

**Comment by rovolution** [comment]
could you attach a screenshot of the print preview to this issue? Thanks

**Comment by bkingsf** [comment]
![slider](https://cloud.githubusercontent.com/assets/6653183/13544842/1b0c5c42-e239-11e5-8ad8-78132cf9fab9.jpg)

**Comment by bkingsf** [comment]
None of the sliders print on your example page: http://seiyria.com/bootstrap-slider/

![slidernotprinting](https://cloud.githubusercontent.com/assets/6653183/13547129/91aba008-e282-11e5-9d26-d4f3302ad49f.jpg)

**Comment by jerrylow** [comment]
One possible method is to add in characters in the print css to show where the elements are. Just testing here:

```css
.slider-track:after {
  content: "------------------------------------------------------------------------------------------";
  height: 2px;
  line-height: 0;
  margin-top: -1px;
  overflow: hidden;
  position: absolute;
  top: 50%;
  white-space: nowrap;
  width: 100%;
}

.slider-handle:after {
  content: "•";
  display: inline-block;
  font-size: 50px;
  height: 15px;
  line-height: 0.3;
  margin-top: -8px;
  position: absolute;
  text-align: center;
  top: 50%;
  width: 100%;
}
```

This will look like:

<img width="529" alt="screen shot 2016-04-13 at 2 37 13 pm" src="https://cloud.githubusercontent.com/assets/984430/14510266/7dfe110e-0185-11e6-8288-89ed12780b6c.png">

Or you could just show the input field that the slider is populating.

I'm not sure if that css fix should be in master though it works with the out of the box demo but once people start playing around with the styles that might not work.
