### ISSUE TITLE
Bootstrap 4 Compatibility

### ISSUE THREAD

**Issue by jeremylynch** [seiyria/bootstrap-slider#689]
Tooltips are not working in bootstrap v4 alpha 6. 

The HTML for tooltips has changed: 

**Bootstrap 3 html:** 
```html
<div class="tooltip top" role="tooltip">
  <div class="tooltip-arrow"></div>
  <div class="tooltip-inner">Tooltip on the left</div>
</div>
```

**Bootstrap 4 html:** 
```html
<div class="tooltip tooltip-top" role="tooltip">
  <div class="tooltip-inner">Tooltip on the top</div>
</div>
```

## We have three things to change: 
1. `.top` is now `.tooltip-top`
2. `.tooltip-arrow` has been removed
3. Change `.in` to `.show`

After making these changes my tooltip position was still wrong. I fixed this with: 

```css
.tooltip.tooltip-main {
  margin-top: -40px;
}
```

**Comment by Shnoulle** [comment]
Maybe, wait for boostrap 4 beta version. alpha is unstable : maybe in was added in some day.

**Comment by seiyria** [comment]
Would be happy to have a PR that adds these classes to the LESS/SCSS files!

**Comment by mrjlynch** [comment]
@seiyria do you think we should just take the bootstrap 3 tooltip SCSS that has been removed in v4 and add it to the bootstrap-slider SCSS?

**Comment by seiyria** [comment]
It'd probably just be a matter of copying and pasting, yes. We don't want any hard reliance on bootstrap.

**Comment by natcohen** [comment]
any chance this can be resolved quickly so we can use bootstrap v4?

**Comment by seiyria** [comment]
Sure, if you submit a PR for it.

**Comment by taha333taha** [comment]
just add : 
.slider.slider-horizontal:hover,
.slider.slider-vertical:hover {
	.tooltip.tooltip-main {
	  opacity: 1 !important;
	}
}

**Comment by str** [comment]
@taha333taha in my case, the tooltip was too big. This is the fix I added to my SCSS:

```SCSS
 .slider.slider-horizontal:hover, .slider.slider-vertical:hover {
    .tooltip.tooltip-main {
        opacity: 0.7 !important;
    }
    .tooltip-inner {
        font-size: 90%;
        width: auto;
    }
}
```
