### ISSUE TITLE
Slider behind modal is bugged

### ISSUE THREAD

**Issue by Invis1ble** [seiyria/bootstrap-slider#705]
Demo: https://jsfiddle.net/dxt5xa7z/1/
Steps to reproduce:
1. Click "show modal" button to show modal. I've changed modal background to transparent for the demo.
2. Move cursor to the top of the `.slider-handle`. Tooltip should be shown.
3. Try to drag slider after tooltip appear. Slider is draggable through modal.

**Comment by Invis1ble** [comment]
Temporary fix:
```css
.slider .tooltip {
    z-index: 1030;
}

.modal .slider .tooltip {
    z-index: 1070;
}
```
