### ISSUE TITLE
Handle goes outside the slider

### ISSUE THREAD

**Issue by malaiselvan** [seiyria/bootstrap-slider#731]
I am customizing this slider with bigger handle with customized image as below

![image](https://cloud.githubusercontent.com/assets/5956639/24127213/ea50ff54-0dca-11e7-8400-9d8411007062.png)

![image](https://cloud.githubusercontent.com/assets/5956639/24127220/f47babbe-0dca-11e7-9c28-90845eca80c8.png)

![image](https://cloud.githubusercontent.com/assets/5956639/24127223/f79ebff2-0dca-11e7-89c7-6637aa6a657a.png)

The handle is the red circle.  In the first 2 images the red circle is inside the slider.  But in the 3rd image the handle goes outside the slider.  The handle should stop when the right end of the circle reaches the end of the slider.

**Comment by seiyria** [comment]
please provide a jsfiddle, although given that you're customizing it that extensively I don't know if there's anything we can do.

**Comment by malaiselvan** [comment]
Find below the jsfiddle link

https://jsfiddle.net/h6q4n6fh/

**Comment by route2Dev** [comment]
Any progress on this issue. We ran into the same issue trying to use a custom image from the slider handle. It seems the slider doesn't take the width of the handle into account when determining how far it can slide.

**Comment by seiyria** [comment]
we'd happily accept a pull request for this.

**Comment by jespirit** [comment]
I made changes to the JSFiddle so that the handler wouldn't go out of bounds.

https://jsfiddle.net/b5rhx9go/1/

```css
.slider.slider-horizontal {
  width: 210px;
  height: 53px; /* changed */
}
.slider.slider-horizontal .slider-track {
  height: 53px; /* changed: same height as the .slider-horizontal height */
  width: 100%;
  margin-top: -26px; /* changed: 1/2 of the height of the .slider-horizontal height */
  top: 50%;
  left: 0;
}

.slider.slider-horizontal .slider-handle.custom {
  background-image: url('http://i65.tinypic.com/2mq3ps9.png');
  width: 63px;
  height: 53px;
  /* top: 5px; */ /* remove this */
  margin-left: -31px; /* 1/2 half the width of the image */
}
```
