### ISSUE TITLE
Looking for a way to prevent value change when clicking the track... force user to use the drag hangle

### ISSUE THREAD

**Issue by sferoze** [seiyria/bootstrap-slider#732]
I would like to prevent value change from clicking the slider track. I want to force the user to select the drag handle and then only change the value. Can you please advise? Thanks

**Comment by sferoze** [comment]
I found a way, this is how, pure css solution. 

```css
.slider {
  pointer-events: none;
}

.slider .slider-handle {
  pointer-events: auto;
}
```
