### ISSUE TITLE
when `@slider-horizontal-width:` is  `100%;` the slider generate horizontal scrolls

### ISSUE THREAD

**Issue by andresgalante** [seiyria/bootstrap-slider#797]
If you set `@slider-horizontal-width:` to  `100%;` the `slider-tick-label` goes beyond the container because the first and last tick label have the same width as the others.

**Comment by seiyria** [comment]
Please provide a jsfiddle.

**Comment by andresgalante** [comment]
Sorry, here it is:

https://codepen.io/andresgalante/pen/eepdNz?editors=1100

**Comment by andresgalante** [comment]
I solved it flexing the container:
```scss
.slider-tick-label-container {
  display: flex;
  justify-content: space-between;
}
```
and removing the js that defines the width and margin left.
